"""add preferred_language and article original_lang

Revision ID: 597e59b2f64c
Revises: 6bd0dd8498a4
Create Date: 2026-08-12 18:02:38.181737

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '597e59b2f64c'
down_revision: str | Sequence[str] | None = '6bd0dd8498a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('original_lang', sa.Enum('FR', 'EN', name='lang'), nullable=False))
    op.add_column('users', sa.Column('preferred_language', sa.Enum('FR', 'EN', name='lang'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('articles', 'original_lang')
    # ### end Alembic commands ###
